### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by ssavinel** [ypereirareis/docker-satis#26]
Using the latest version of the docker image, satis returns a 403 error. It seems like Supervisor is not launched at startup.
I would gladly provide more infos if you could tell me where to find them.

**Comment by ypereirareis** [comment]
Hi !

Actually, do you wait enough time to let all the services start ??

You can use this command to see what happen on container statup

`docker logs -f CONTAINER_NAME_OR_ID`

Bye

**Comment by ssavinel** [comment]
This issue seems to be linked to #27 . Changing the rights of the file in the script made the script end flawlessly and satis start correctly.
