### ISSUE TITLE
config.json not writeable

### ISSUE THREAD

**Issue by ssavinel** [ypereirareis/docker-satis#28]
Adding a repo to satis through the admin interface returns two exceptions :
`IOException in FilePersister.php line 117: Path "/app/config.json" is not writeable.`
and
`RuntimeException in FilePersister.php line 82: Unable to persist the data to "/app/config.json"`
The file is set through a volume with  : `./data/config/config.json:/app/config.json:rw`and if I edit it on the host or in the docker container, in can see the changes both way. 
Why isn't it writeable through satisfy ? rights conflicts between `www-data` and `root` ?

**Comment by ssavinel** [comment]
Okay, seems like the error was on my side. Right were rewritten by my VM... Guess we can close.
Sorry for the inconvenience.

**Comment by ypereirareis** [comment]
OK no pbl !

Bye !
