### ISSUE TITLE
403 Forbiden

### ISSUE THREAD

**Issue by jmverges** [ypereirareis/docker-satis#36]
Hello there,

I'm struggling with this repository. Satisfy is returning ok but satis itself is returning 403 when I edit the config.json. I'm using a custom docker image based on 4.1. Could I get any hint? here a log: https://gist.github.com/jmverges/77a87b6a1384156a99e1ee61c870a6da

Regards,
Juan Manuel.

**Comment by ypereirareis** [comment]
Hello,

I think the error is clear enough.
You need to have the correct credentials to clone the repo.
Share your ssh key or maybe the problme comes from a missing github API token you should add the the image.

Bye.

**Comment by jmverges** [comment]
Hello @ypereirareis,

We are having a custom docker image based on this docker image. We discovered this:

satis:  
  environment:
    PRIVATE_REPO_DOMAIN_LIST: ourownreposity.com

is not populated in the ./startup.sh so our know_hosts file is not properly. If we start the ./startup.sh manually we are ask to trust in our own private domain. Once we accept this manually, everything is working properly. 

Could you provide some hint?

Regards,
Juan Manuel.

**Comment by ypereirareis** [comment]
Hi,

if everything is fine you shouldn't be asked to add the fingerprint manually.
The this the aim of the script (to add servers fingerprint into known_hosts file).

I think the pbl comes from your server repo.
Try executing this manually from the satis container:

```
ssh-keyscan -t rsa ourownreposity.com
```
- What is the output ?
- Is your serveur protected by rsa key ?
- Is your ssh port 22 ?

**Comment by ypereirareis** [comment]
Old and no response.
