### ISSUE TITLE
Persist Satis build 

### ISSUE THREAD

**Issue by andrefigueira** [ypereirareis/docker-satis#52]
Hi There,

Looking at getting this setup for our dev environment, but can't see how to persist the satis builds so that they survive docker restarts?

Cheers

**Comment by ypereirareis** [comment]
Hi !

Actually I don't really understand what you need.
Data is not supposed to be lost when a container or even docker is restarted.
Data is destroyed/removed if you remove (`docker rm`) container and you have no volume for your container.

So maybe the solution you are looking for is to add a volume to persist the data on your host.

Bye.
