### ISSUE TITLE
Ubuntu 15.10 EOL, update image to 16.04 or 18.04

### ISSUE THREAD

**Issue by Doqnach** [ypereirareis/docker-satis#54]
The current image uses Ubuntu 15.10 as a base, which has been EOL since July 28, 2016.

Updating this to 16.04 or 18.04 does require either adding `ppa:ondrej/php` repo to apt (This drops support for `php-apc` though since this does not seem available anymore for PHP 5.6), or switching to php7.

I didn't test what switching PHP versions would do, but either solution makes sure that at least the OS is still supported for a while to come.

**Comment by yi01184** [comment]
Made the following changes:

`FROM ubuntu:18.04`

`RUN apt-get update && apt-get install -y --force-yes --no-install-recommends \
        build-essential \
        software-properties-common \
        cron \
        nano \
        git \
        curl \
        supervisor \
        libapache2-mod-php7.2 \
        php7.2-cli \
        php7.2-json \
        php7.2-curl \
        php7.2-fpm \
        php7.2-gd \
        php7.2-ldap \
        php7.2-mbstring \
        php7.2-mysql \
        php7.2-soap \
        php7.2-sqlite3 \
        php7.2-xml \
        php7.2-zip \
        php7.2-intl \
        php-imagick \
        nginx \
        ssh \
        npm \
        && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
`


`RUN sed -i "s/;date.timezone =.*/date.timezone = UTC/" /etc/php/7.2/fpm/php.ini \
        && sed -i "s/;date.timezone =.*/date.timezone = UTC/" /etc/php/7.2/cli/php.ini \
        && echo "daemon off;" >> /etc/nginx/nginx.conf \
        && sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php/7.2/fpm/php-fpm.conf \
        && sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php/7.2/fpm/php.ini
`
Which worked for me...

**Comment by ypereirareis** [comment]
Image now uses debian buster, PHP7.4, Satisfy 3.3.0 and last version of composer 1+
