### ISSUE TITLE
Build problem with --force-yes

### ISSUE THREAD

**Issue by ephrin** [ypereirareis/docker-satis#9]
E: There are problems and -y was used without --force-yes
Service 'satis' failed to build: The command [/bin/sh -c apt-get install -y nginx] returned a non-zero code: 100

**Comment by ypereirareis** [comment]
Fixing this... wait for it.

**Comment by ypereirareis** [comment]
OK, everything should be fine now, just wait until DOcker Hub has rebuilt the image.... or build it yourself with : 

```
docker build -t ypereirareis/docker-satis .
```

**Comment by ephrin** [comment]
cool. thanks
